-- Backfill descriptions for the default experience rows so the running site
-- shows the new write-ups without a template re-save.

UPDATE portfolio_experiences SET description = 'Ran self-hosted infrastructure for 5 companies across Hetzner, Hostinger and OVH Cloud — Dokploy and Coolify-managed VPS fleets with Nginx, Traefik, Cloudflare and Portainer handling routing, SSL and container orchestration, with full server ownership and access management. Built multi-cloud pipelines across AWS (EC2, RDS, S3, Lambda, API Gateway, Route53, VPC) and GCP (GKE, GCS, Cloud Functions), offloading serverless workloads to Vercel, Lambda and Cloudflare Workers and wiring everything through Jenkins and GitHub Actions with Docker for staging and prod. Set up per-client observability — Prometheus, Grafana, Uptime Kuma, Sentry and PostHog for the infra, GA4, Search Console, Bing Webmaster Tools and Umami for product analytics. Shipped application layers on Next.js, tRPC, PostgreSQL, Redis, Turso and Convex, from relational cores to real-time sync and edge databases, plus the backend services powering each product.' WHERE title LIKE '%Singularity Works%';

UPDATE portfolio_experiences SET description = 'Built WebSocket APIs and the backend for a multi-tenant HRMS on the MERN stack — real-time CRUD over Socket.IO for employee records, attendance and approvals, powering admin and super-admin dashboards with role-scoped access. Developed RESTful APIs with FastAPI to manage concurrent video streams in a multi-camera security system, handling stream session lifecycle, frame-rate throttling and multi-client fan-out under load.' WHERE title LIKE '%amasQIS%';

UPDATE portfolio_experiences SET description = 'Led the people behind the browser club — managed cross-functional club operations, coordinated team leads and kept the community running between semesters. Translated complex technical topics into content people actually wanted to read, producing written and visual material on web standards, open-source tooling and developer culture. Built real-time multiplayer games with live leaderboards, cooperative sabotage hints and pair mechanics for community events.' WHERE title LIKE '%Mozilla Firefox Club%';

UPDATE portfolio_experiences SET description = 'Kept the machine running — logistics, team coordination and the operational groundwork that let the technical people ship without friction. Developed a treasure-hunt app with an admin dashboard on MongoDB, Express, React and Node.js, implementing REST and WebSocket APIs for real-time participant tracking, game-state updates and scoring. Leveraged EC2 with Docker for containerized, scalable hosting under player traffic, and built the event websites plus the AI Club landing page on the MERN stack.' WHERE title LIKE '%AI Club%';

UPDATE portfolio_experiences SET description = 'Collaborated with a senior developer to enhance a non-profit website — my first commercial frontend work. The project focused on improving online visibility and making donations frictionless, expanding the organization''s reach to a broader audience and showcasing the work it does for children who lack proper education, books and food.' WHERE title LIKE '%Operation Smile%';
