-- New copy for asocialmedia, amemorymachine, lumen and papyrus
-- (papyrus also gets a new title).

UPDATE portfolio_projects SET description = $$asocialmedia (formerly zephyr), the last social platform you'll ever need. now with a cast that talks back.Your internet, unified: feed, communities, real-time chat, rich media, tipping. Powered by Aura, a reputation system that levels with you, and a Cast, characters with their own personas, takes, and beef, who actually read your posts and show up in the comments to agree, argue, or roast you. Zeph's just the one you know best. Built by one person. Ambition: unhinged.$$ WHERE title LIKE 'asocialmedia%';

UPDATE portfolio_projects SET description = $$amemorymachine. built because your brain forgets and your notes app doesn't retrieve. Everything I read, write, hear, or scribble gets ingested, indexed, and made retrievable. OCR pulls text out of images and scans, STT turns voice into notes, TTS reads them back. Runs on local or self-hosted LLMs, no data leaving unless I say so. Notes live as a RAG graph, not a folder tree, so context surfaces on its own instead of getting buried. Realtime markdown docs, Notion-style editing, but the memory underneath actually connects things.$$ WHERE title LIKE 'amemorymachine%';

UPDATE portfolio_projects SET description = $$Lumen. a spatial system for organizing work, infinite canvas, not another kanban board.Local-first spatial workspace where tasks live on an infinite canvas instead of a fixed board. Free-form kanban when you want to think in space, structured tasks when you need actual deadlines, offline-first so it survives dropped connections and closed laptops. Realtime collab with no lag, built on CRDTs so two people editing the same board never fight each other. RAG-backed AI reads the whole canvas, not just one card, so you can ask it what's actually going on instead of digging through columns yourself.$$ WHERE title LIKE 'Lumen%';

UPDATE portfolio_projects SET title = $$Papyrus. a spreadsheet that syncs like a doc and scales like a database.$$, description = $$Realtime collaborative spreadsheet, local-first, so it works before the network catches up. CRDT-based syncing means every edit merges cleanly, no last-write-wins, no overwritten formulas. Evaluation runs off the main thread in a worker, so the grid never freezes while it's computing. Virtualized rendering keeps it responsive past 10K+ rows, scrolling and editing stay instant even when the sheet gets heavy. Built for the moment spreadsheets usually fall apart.$$ WHERE title LIKE 'Papyrus%';
